### ISSUE TITLE
JSON redesign

### ISSUE THREAD

**Issue by genofire** [ffnord/meshviewer#28]
Hi,
we what to develop a `respondd` collector for some things
 and also for the meshviewer (and influxdb for interesting people).
I recognise that there are a few unbeautif things in there.
1. the nodes.json has not the structur like the respondd answer
   (we know https://github.com/freifunk-gluon/gluon/issues/522, nothing matter).
   As example, there are multiple `statistics.clients` like `total`, `wifi`, `wifi24` and `wifi5`.
2. the graph.json works with array positions.
   It is only necessary to use the nodeid like:
   
   ``` json
   "links":[
       {
           "source":"feedl33d",
           "target":"1001110d",
           "bidirect":true,
           "vpn":true,
           "tq":32
       }
   ]
   ```

I would make a PR to make this meshviewer compatible with this changes
if somebody agree with it.

**Comment by lost-tty** [comment]
1) This is by design. The idea was to make the meshviewer API independent from the node's data structures. If anything, a redesign should make it match the [NetJSON](http://netjson.org/) format (once it's finalized). From what I've gathered, NetJSON might not yet be suitable for meshviewer.

2) This is also by design. It does not suffice to use the node id directly as the links do only refer to nodes within the nodes list from graph.json. This node list does refer to node ids. There may be nodes within the graph that do not have a corresponding node id (e.g. nodes seen via weak wifi links).

**Comment by genofire** [comment]
I should make two issues:
1) okay i got it. (a change to show the different clients would be accepted? ) -> closed

2) I does not understand:
I have not seen any code, where the node id would not be in a answer.
Okay the mac could be different as the node id in a answer, but the had to replace by the node id.

**Comment by lost-tty** [comment]
Have a look at this: https://github.com/ffnord/meshviewer/blob/master/lib/main.js#L33

**Comment by genofire** [comment]
_This is no answer :(
I know how you make it to manage your json tree ^^
Sorry that i am wasting your time._

i have make it for testing, maybe you could just look :D
https://github.com/FreifunkBremen/meshviewer/blob/JSONv2/lib/main.js#L45

**Comment by lost-tty** [comment]
I see. Well, I think it's best to keep the format as is for maximum compatibility until we can be sure that for each node within the graph a nodeinfo object is present.

**Comment by genofire** [comment]
okay that is a answer.
Not beautiful but acceptable.
